
object TaskRuleId:String
object TaskRulesPerPage:Integer
object TotalTaskRulesCount:Integer

object TaskRule
    id:TaskRuleId
    createdOn:CreatedOn
    createdBy:EmployeeId
    ifBlock:TaskRuleIfBlock
    thenBlock:TaskRuleThenBlock


persistent object TestCatalog: AccountId[*]

procedure EntryPoint()
    // TaskRule = new TaskRule(
    //     createdBy = "Test"
    // )
    // SourceDescription.GetPatternForSourceDescriptionMatch()
