procedure DoSomethingUnique(Params)
    LogInfo("Unique")
    UnknownService.internalProcedure()

procedure internalProcedure()
    call DoSomethingUnique(Params)
    // let ObjectForFormula = new
    SomeObject.ToObjectForFormula()
    let T = new Test;


object ObjectForFormula
    test1:String
    test2: Date

formula ToObjectForFormula(String):ObjectForFormula = new Test

object SomeObject: String
